SET DEFINE OFF;


--Table of Excel Dataset Content
CREATE TABLE ITD_TT_EXCEL_DATASET_CONTENT
(
	DA_PURCHASE				DATE NOT NULL,
	CO_INVOICE				VARCHAR2(20) NOT NULL,
	NA_CUSTOMER_ROOT		VARCHAR2(100) NOT NULL,
	NA_CUSTOMER_LEAF		VARCHAR2(100) NOT NULL,
	DE_PRODUCT				VARCHAR2(100) NOT NULL,
	NA_PACK_SIZE			VARCHAR2(100) NOT NULL,
	NA_UNIT_TYPE			VARCHAR2(100) NOT NULL,
	NA_CATEGORY				VARCHAR2(100) NOT NULL,
	NA_DISTRIBUTOR_ROOT		VARCHAR2(100) NOT NULL,
	NA_DISTRIBUTOR_LEAF		VARCHAR2(100) NOT NULL,
	NA_MANUFACTURER			VARCHAR2(100) NOT NULL,
	AM_QUANTITY				NUMBER(10,2) NOT NULL,
	AM_PRICE				NUMBER(10,2) NOT NULL,
	AM_TOTAL				NUMBER(10,2) NOT NULL
);

COMMENT ON TABLE ITD_TT_EXCEL_DATASET_CONTENT IS 'Excel Dataset Content';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.DA_PURCHASE IS 'Column "Purchase Date"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.CO_INVOICE IS 'Column "Invoice"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_CUSTOMER_ROOT IS 'Column "Customer Root"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_CUSTOMER_LEAF IS 'Column "Customer Leaf"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.DE_PRODUCT IS 'Column "Product Description"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_PACK_SIZE IS 'Column "Pack Size"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_UNIT_TYPE IS 'Column "Unit Type"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_CATEGORY IS 'Column "Category"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_DISTRIBUTOR_ROOT IS 'Column "Distributor Root"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_DISTRIBUTOR_LEAF IS 'Column "Distributor Leaf"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.NA_MANUFACTURER IS 'Column "Manufacturer"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.AM_QUANTITY IS 'Column "Quantity"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.AM_PRICE IS 'Column "Price"';
COMMENT ON COLUMN ITD_TT_EXCEL_DATASET_CONTENT.AM_TOTAL IS 'Column "Total"';
