SET DEFINE OFF;


--Table of Cities
CREATE TABLE ITD_DT_CITY
(
	ID_CITY		NUMBER(38,0) NOT NULL,
	CO_CITY		VARCHAR2(10) NOT NULL,
	CONSTRAINT ITD_DT_CITY_PK PRIMARY KEY(ID_CITY)
);

COMMENT ON TABLE ITD_DT_CITY IS 'Cities';
COMMENT ON COLUMN ITD_DT_CITY.ID_CITY IS 'ID of the city';
COMMENT ON COLUMN ITD_DT_CITY.CO_CITY IS 'Code of the city';


--Table of Customers Root
CREATE TABLE ITD_DT_CUSTOMER_ROOT
(
	ID_CUSTOMER_ROOT	NUMBER(38,0) NOT NULL,
	NA_CUSTOMER_ROOT	VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_CUSTOMER_ROOT_PK PRIMARY KEY(ID_CUSTOMER_ROOT)
);

COMMENT ON TABLE ITD_DT_CUSTOMER_ROOT IS 'Customers Root';
COMMENT ON COLUMN ITD_DT_CUSTOMER_ROOT.ID_CUSTOMER_ROOT IS 'ID of the customer root';
COMMENT ON COLUMN ITD_DT_CUSTOMER_ROOT.NA_CUSTOMER_ROOT IS 'Name of the customer root';


--Table of Customers Leaf
CREATE TABLE ITD_DT_CUSTOMER_LEAF
(
	ID_CUSTOMER_LEAF	NUMBER(38,0) NOT NULL,
	ID_CUSTOMER_ROOT	NUMBER(38,0) NOT NULL,
	ID_CITY				NUMBER(38,0) NOT NULL,
	NA_CUSTOMER_LEAF	VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_CUSTOMER_LEAF_PK PRIMARY KEY(ID_CUSTOMER_LEAF)
);
ALTER TABLE ITD_DT_CUSTOMER_LEAF
	ADD CONSTRAINT ITD_D_CULE_REF_D_CURO_FK
	FOREIGN KEY(ID_CUSTOMER_ROOT) REFERENCES ITD_DT_CUSTOMER_ROOT(ID_CUSTOMER_ROOT);
ALTER TABLE ITD_DT_CUSTOMER_LEAF
	ADD CONSTRAINT ITD_D_CULE_REF_D_CITY_FK
	FOREIGN KEY(ID_CITY) REFERENCES ITD_DT_CITY(ID_CITY);

COMMENT ON TABLE ITD_DT_CUSTOMER_LEAF IS 'Customers Leaf';
COMMENT ON COLUMN ITD_DT_CUSTOMER_LEAF.ID_CUSTOMER_LEAF IS 'ID of the customer leaf';
COMMENT ON COLUMN ITD_DT_CUSTOMER_LEAF.ID_CUSTOMER_ROOT IS 'ID of the customer root. Foreign key towards the table ITD_DT_CUSTOMER_ROOT';
COMMENT ON COLUMN ITD_DT_CUSTOMER_LEAF.ID_CITY IS 'ID of the city. Foreign key towards the table ITD_DT_CITY';
COMMENT ON COLUMN ITD_DT_CUSTOMER_LEAF.NA_CUSTOMER_LEAF IS 'Name of the customer leaf';


--Table of Distributors Root
CREATE TABLE ITD_DT_DISTRIBUTOR_ROOT
(
	ID_DISTRIBUTOR_ROOT		NUMBER(38,0) NOT NULL,
	NA_DISTRIBUTOR_ROOT		VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_DISTRIBUTOR_ROOT_PK PRIMARY KEY(ID_DISTRIBUTOR_ROOT)
);

COMMENT ON TABLE ITD_DT_DISTRIBUTOR_ROOT IS 'Distributors Root';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_ROOT.ID_DISTRIBUTOR_ROOT IS 'ID of the distributor root';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_ROOT.NA_DISTRIBUTOR_ROOT IS 'Name of the distributor root';


--Table of Distributors Leaf
CREATE TABLE ITD_DT_DISTRIBUTOR_LEAF
(
	ID_DISTRIBUTOR_LEAF		NUMBER(38,0) NOT NULL,
	ID_DISTRIBUTOR_ROOT		NUMBER(38,0) NOT NULL,
	ID_CITY					NUMBER(38,0) NOT NULL,
	NA_DISTRIBUTOR_LEAF		VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_DISTRIBUTOR_LEAF_PK PRIMARY KEY(ID_DISTRIBUTOR_LEAF)
);
ALTER TABLE ITD_DT_DISTRIBUTOR_LEAF
	ADD CONSTRAINT ITD_D_DILE_REF_D_DIRO_FK
	FOREIGN KEY(ID_DISTRIBUTOR_ROOT) REFERENCES ITD_DT_DISTRIBUTOR_ROOT(ID_DISTRIBUTOR_ROOT);
ALTER TABLE ITD_DT_DISTRIBUTOR_LEAF
	ADD CONSTRAINT ITD_D_DILE_REF_D_CITY_FK
	FOREIGN KEY(ID_CITY) REFERENCES ITD_DT_CITY(ID_CITY);

COMMENT ON TABLE ITD_DT_DISTRIBUTOR_LEAF IS 'Distributors Leaf';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_LEAF.ID_DISTRIBUTOR_LEAF IS 'ID of the distributor leaf';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_LEAF.ID_DISTRIBUTOR_ROOT IS 'ID of the distributor root. Foreign key towards the table ITD_DT_DISTRIBUTOR_ROOT';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_LEAF.ID_CITY IS 'ID of the city. Foreign key towards the table ITD_DT_CITY';
COMMENT ON COLUMN ITD_DT_DISTRIBUTOR_LEAF.NA_DISTRIBUTOR_LEAF IS 'Name of the distributor leaf';


--Table of Manufacturers
CREATE TABLE ITD_DT_MANUFACTURER
(
	ID_MANUFACTURER		NUMBER(38,0) NOT NULL,
	NA_MANUFACTURER		VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_MANUFACTURER_PK PRIMARY KEY(ID_MANUFACTURER)
);

COMMENT ON TABLE ITD_DT_MANUFACTURER IS 'Manufacturers';
COMMENT ON COLUMN ITD_DT_MANUFACTURER.ID_MANUFACTURER IS 'ID of the manufacturer';
COMMENT ON COLUMN ITD_DT_MANUFACTURER.NA_MANUFACTURER IS 'Name of the manufacturer';


--Table of Categories
CREATE TABLE ITD_DT_CATEGORY
(
	ID_CATEGORY		NUMBER(38,0) NOT NULL,
	NA_CATEGORY		VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_CATEGORY_PK PRIMARY KEY(ID_CATEGORY)
);

COMMENT ON TABLE ITD_DT_CATEGORY IS 'Categories';
COMMENT ON COLUMN ITD_DT_CATEGORY.ID_CATEGORY IS 'ID of the category';
COMMENT ON COLUMN ITD_DT_CATEGORY.NA_CATEGORY IS 'Name of the category';


--Table of Unit Types
CREATE TABLE ITD_DT_UNIT_TYPE
(
	ID_UNIT_TYPE	NUMBER(38,0) NOT NULL,
	NA_UNIT_TYPE	VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_UNIT_TYPE_PK PRIMARY KEY(ID_UNIT_TYPE)
);

COMMENT ON TABLE ITD_DT_UNIT_TYPE IS 'Unit Types';
COMMENT ON COLUMN ITD_DT_UNIT_TYPE.ID_UNIT_TYPE IS 'ID of the unit type';
COMMENT ON COLUMN ITD_DT_UNIT_TYPE.NA_UNIT_TYPE IS 'Name of the unit type';


--Table of Pack Sizes
CREATE TABLE ITD_DT_PACK_SIZE
(
	ID_PACK_SIZE	NUMBER(38,0) NOT NULL,
	NA_PACK_SIZE	VARCHAR2(100) NOT NULL,
	CONSTRAINT ITD_DT_PACK_SIZE_PK PRIMARY KEY(ID_PACK_SIZE)
);

COMMENT ON TABLE ITD_DT_PACK_SIZE IS 'Pack Sizes';
COMMENT ON COLUMN ITD_DT_PACK_SIZE.ID_PACK_SIZE IS 'ID of the pack size';
COMMENT ON COLUMN ITD_DT_PACK_SIZE.NA_PACK_SIZE IS 'Name of the pack size';


--Table of Products
CREATE TABLE ITD_DT_PRODUCT
(
	ID_PRODUCT			NUMBER(38,0) NOT NULL,
	DE_PRODUCT			VARCHAR2(100) NOT NULL,
	ID_MANUFACTURER		NUMBER(38,0) NOT NULL,
	ID_CATEGORY			NUMBER(38,0) NOT NULL,
	CONSTRAINT ITD_DT_PRODUCT_PK PRIMARY KEY(ID_PRODUCT)
);
ALTER TABLE ITD_DT_PRODUCT
	ADD CONSTRAINT ITD_D_PROD_REF_D_MANU_FK
	FOREIGN KEY(ID_MANUFACTURER) REFERENCES ITD_DT_MANUFACTURER(ID_MANUFACTURER);
ALTER TABLE ITD_DT_PRODUCT
	ADD CONSTRAINT ITD_D_PROD_REF_D_CATE_FK
	FOREIGN KEY(ID_CATEGORY) REFERENCES ITD_DT_CATEGORY(ID_CATEGORY);

COMMENT ON TABLE ITD_DT_PRODUCT IS 'Products';
COMMENT ON COLUMN ITD_DT_PRODUCT.ID_PRODUCT IS 'ID of the product';
COMMENT ON COLUMN ITD_DT_PRODUCT.DE_PRODUCT IS 'Description of the product';
COMMENT ON COLUMN ITD_DT_PRODUCT.ID_MANUFACTURER IS 'ID of the manufacturer. Foreign key towards the table ITD_DT_MANUFACTURER';
COMMENT ON COLUMN ITD_DT_PRODUCT.ID_CATEGORY IS 'ID of the category. Foreign key towards the table ITD_DT_CATEGORY';


--Table of Products per Purchase
CREATE TABLE ITD_FT_PRODUCT_PURCHASE
(
	ID_PRODUCT_PURCHASE			NUMBER(38,0) NOT NULL,
	CO_INVOICE					VARCHAR2(20) NOT NULL,
	DA_PURCHASE					DATE NOT NULL,
	YE_PURCHASE					NUMBER(4,0) NOT NULL,
	MO_PURCHASE					NUMBER(2,0) NOT NULL,
	DM_PURCHASE					NUMBER(2,0) NOT NULL,
	FM_PURCHASE					VARCHAR2(7) NOT NULL,
	ID_CUSTOMER_ROOT			NUMBER(38,0) NOT NULL,
	ID_CUSTOMER_LEAF			NUMBER(38,0) NOT NULL,
	ID_CITY_CUSTOMER_LEAF		NUMBER(38,0) NOT NULL,
	ID_PRODUCT					NUMBER(38,0) NOT NULL,
	ID_MANUFACTURER				NUMBER(38,0) NOT NULL,
	ID_CATEGORY					NUMBER(38,0) NOT NULL,
	ID_UNIT_TYPE				NUMBER(38,0) NOT NULL,
	ID_PACK_SIZE				NUMBER(38,0) NOT NULL,
	ID_DISTRIBUTOR_ROOT			NUMBER(38,0) NOT NULL,
	ID_DISTRIBUTOR_LEAF			NUMBER(38,0) NOT NULL,
	ID_CITY_DISTRIBUTOR_LEAF	NUMBER(38,0) NOT NULL,
	AM_QUANTITY					NUMBER(10,2) NOT NULL,
	AM_PRICE					NUMBER(10,2) NOT NULL,
	AM_TOTAL					NUMBER(10,2) NOT NULL,
	CONSTRAINT ITD_FT_PRODUCT_PURCHASE_PK PRIMARY KEY(ID_PRODUCT_PURCHASE)
);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_CURO_FK
	FOREIGN KEY(ID_CUSTOMER_ROOT) REFERENCES ITD_DT_CUSTOMER_ROOT(ID_CUSTOMER_ROOT);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_CULE_FK
	FOREIGN KEY(ID_CUSTOMER_LEAF) REFERENCES ITD_DT_CUSTOMER_LEAF(ID_CUSTOMER_LEAF);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_CICL_FK
	FOREIGN KEY(ID_CITY_CUSTOMER_LEAF) REFERENCES ITD_DT_CITY(ID_CITY);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_PROD_FK
	FOREIGN KEY(ID_PRODUCT) REFERENCES ITD_DT_PRODUCT(ID_PRODUCT);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_MANU_FK
	FOREIGN KEY(ID_MANUFACTURER) REFERENCES ITD_DT_MANUFACTURER(ID_MANUFACTURER);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_CATE_FK
	FOREIGN KEY(ID_CATEGORY) REFERENCES ITD_DT_CATEGORY(ID_CATEGORY);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_UNTY_FK
	FOREIGN KEY(ID_UNIT_TYPE) REFERENCES ITD_DT_UNIT_TYPE(ID_UNIT_TYPE);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_PASI_FK
	FOREIGN KEY(ID_PACK_SIZE) REFERENCES ITD_DT_PACK_SIZE(ID_PACK_SIZE);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_DIRO_FK
	FOREIGN KEY(ID_DISTRIBUTOR_ROOT) REFERENCES ITD_DT_DISTRIBUTOR_ROOT(ID_DISTRIBUTOR_ROOT);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_DILE_FK
	FOREIGN KEY(ID_DISTRIBUTOR_LEAF) REFERENCES ITD_DT_DISTRIBUTOR_LEAF(ID_DISTRIBUTOR_LEAF);
ALTER TABLE ITD_FT_PRODUCT_PURCHASE
	ADD CONSTRAINT ITD_F_PRPU_REF_D_CIDL_FK
	FOREIGN KEY(ID_CITY_DISTRIBUTOR_LEAF) REFERENCES ITD_DT_CITY(ID_CITY);

COMMENT ON TABLE ITD_FT_PRODUCT_PURCHASE IS 'Products per Purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_PRODUCT_PURCHASE IS 'ID of the product per purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.CO_INVOICE IS 'Code of the invoice';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.DA_PURCHASE IS 'Date of the purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.YE_PURCHASE IS 'Year of the purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.MO_PURCHASE IS 'Month of the purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.DM_PURCHASE IS 'Day of the month of the purchase';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.FM_PURCHASE IS 'Full month of the purchase (yyyy-MM)';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_CUSTOMER_ROOT IS 'ID of the customer root. Foreign key towards the table ITD_DT_CUSTOMER_ROOT';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_CUSTOMER_LEAF IS 'ID of the customer leaf. Foreign key towards the table ITD_DT_CUSTOMER_LEAF';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_CITY_CUSTOMER_LEAF IS 'ID of the city of the customer leaf. Foreign key towards the table ITD_DT_CITY';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_PRODUCT IS 'ID of the product. Foreign key towards the table ITD_DT_PRODUCT';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_MANUFACTURER IS 'ID of the manufacturer. Foreign key towards the table ITD_DT_MANUFACTURER';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_CATEGORY IS 'ID of the category. Foreign key towards the table ITD_DT_CATEGORY';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_UNIT_TYPE IS 'ID of the unit type. Foreign key towards the table ITD_DT_UNIT_TYPE';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_PACK_SIZE IS 'ID of the pack size. Foreign key towards the table ITD_DT_PACK_SIZE';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_DISTRIBUTOR_ROOT IS 'ID of the distributor root. Foreign key towards the table ITD_DT_DISTRIBUTOR_ROOT';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_DISTRIBUTOR_LEAF IS 'ID of the distributor leaf. Foreign key towards the table ITD_DT_DISTRIBUTOR_LEAF';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.ID_CITY_DISTRIBUTOR_LEAF IS 'ID of the city of the distributor leaf. Foreign key towards the table ITD_DT_CITY';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.AM_QUANTITY IS 'Quantity of the product';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.AM_PRICE IS 'Price of the product';
COMMENT ON COLUMN ITD_FT_PRODUCT_PURCHASE.AM_TOTAL IS 'Total of the product';
