SET DEFINE OFF;


--Filling table of cities
INSERT INTO ITD_DT_CITY(ID_CITY, CO_CITY)
SELECT ID_CITY, CO_CITY 
FROM ITD_MT_CITY
ORDER BY 1;


--Filling table of customers root
INSERT INTO ITD_DT_CUSTOMER_ROOT(ID_CUSTOMER_ROOT, NA_CUSTOMER_ROOT)
SELECT ID_CUSTOMER_ROOT, NA_CUSTOMER_ROOT 
FROM ITD_MT_CUSTOMER_ROOT
ORDER BY 1;


--Filling table of customers leaf
INSERT INTO ITD_DT_CUSTOMER_LEAF(ID_CUSTOMER_LEAF, ID_CUSTOMER_ROOT, ID_CITY, NA_CUSTOMER_LEAF)
SELECT CL.ID_CUSTOMER_LEAF, CL.ID_CUSTOMER_ROOT, CL.ID_CITY, CR.NA_CUSTOMER_ROOT || ' - ' || C.CO_CITY 
FROM ITD_MT_CUSTOMER_LEAF CL
INNER JOIN ITD_MT_CUSTOMER_ROOT CR ON CR.ID_CUSTOMER_ROOT = CL.ID_CUSTOMER_ROOT
INNER JOIN ITD_MT_CITY C ON C.ID_CITY = CL.ID_CITY
ORDER BY 1;


--Filling table of distributors root
INSERT INTO ITD_DT_DISTRIBUTOR_ROOT(ID_DISTRIBUTOR_ROOT, NA_DISTRIBUTOR_ROOT)
SELECT ID_DISTRIBUTOR_ROOT, NA_DISTRIBUTOR_ROOT 
FROM ITD_MT_DISTRIBUTOR_ROOT
ORDER BY 1;


--Filling table of distributors leaf
INSERT INTO ITD_DT_DISTRIBUTOR_LEAF(ID_DISTRIBUTOR_LEAF, ID_DISTRIBUTOR_ROOT, ID_CITY, NA_DISTRIBUTOR_LEAF)
SELECT DL.ID_DISTRIBUTOR_LEAF, DL.ID_DISTRIBUTOR_ROOT, DL.ID_CITY, DR.NA_DISTRIBUTOR_ROOT || ' - ' || C.CO_CITY 
FROM ITD_MT_DISTRIBUTOR_LEAF DL
INNER JOIN ITD_MT_DISTRIBUTOR_ROOT DR ON DR.ID_DISTRIBUTOR_ROOT = DL.ID_DISTRIBUTOR_ROOT
INNER JOIN ITD_MT_CITY C ON C.ID_CITY = DL.ID_CITY
ORDER BY 1;


--Filling table of manufacturers
INSERT INTO ITD_DT_MANUFACTURER(ID_MANUFACTURER, NA_MANUFACTURER)
SELECT ID_MANUFACTURER, NA_MANUFACTURER
FROM ITD_MT_MANUFACTURER
ORDER BY 1;


--Filling table of categories
INSERT INTO ITD_DT_CATEGORY(ID_CATEGORY, NA_CATEGORY)
SELECT ID_CATEGORY, NA_CATEGORY
FROM ITD_MT_CATEGORY
ORDER BY 1;


--Filling table of unit types
INSERT INTO ITD_DT_UNIT_TYPE(ID_UNIT_TYPE, NA_UNIT_TYPE)
SELECT ID_UNIT_TYPE, NA_UNIT_TYPE
FROM ITD_MT_UNIT_TYPE
ORDER BY 1;


--Filling table of pack sizes
INSERT INTO ITD_DT_PACK_SIZE(ID_PACK_SIZE, NA_PACK_SIZE)
SELECT ID_PACK_SIZE, NA_PACK_SIZE
FROM ITD_MT_PACK_SIZE
ORDER BY 1;


--Filling table of products
INSERT INTO ITD_DT_PRODUCT(ID_PRODUCT, DE_PRODUCT, ID_MANUFACTURER, ID_CATEGORY)
SELECT ID_PRODUCT, DE_PRODUCT, ID_MANUFACTURER, ID_CATEGORY
FROM ITD_MT_PRODUCT
ORDER BY 1;


--Filling table de products per purchase
INSERT INTO ITD_FT_PRODUCT_PURCHASE
(
	ID_PRODUCT_PURCHASE, CO_INVOICE, 
	DA_PURCHASE, YE_PURCHASE, MO_PURCHASE, DM_PURCHASE, FM_PURCHASE, 
	ID_CUSTOMER_ROOT, ID_CUSTOMER_LEAF, ID_CITY_CUSTOMER_LEAF, 
	ID_PRODUCT, ID_MANUFACTURER, ID_CATEGORY, ID_UNIT_TYPE, ID_PACK_SIZE, 
	ID_DISTRIBUTOR_ROOT, ID_DISTRIBUTOR_LEAF, ID_CITY_DISTRIBUTOR_LEAF, 
	AM_QUANTITY, AM_PRICE, AM_TOTAL
)
SELECT 
	PP.ID_PRODUCT_PURCHASE, P.CO_INVOICE, 
	P.DA_PURCHASE, EXTRACT(YEAR FROM P.DA_PURCHASE), EXTRACT(MONTH FROM P.DA_PURCHASE), EXTRACT(DAY FROM P.DA_PURCHASE), EXTRACT(YEAR FROM P.DA_PURCHASE) || '-' || LPAD(EXTRACT(MONTH FROM P.DA_PURCHASE), 2, '0'), 
	P.ID_CUSTOMER_ROOT, P.ID_CUSTOMER_LEAF, CL.ID_CITY, 
	PP.ID_PRODUCT, PP.ID_MANUFACTURER, PP.ID_CATEGORY, PP.ID_UNIT_TYPE, PP.ID_PACK_SIZE, 
	PP.ID_DISTRIBUTOR_ROOT, PP.ID_DISTRIBUTOR_LEAF, DL.ID_CITY, 
	PP.AM_QUANTITY, PP.AM_PRICE, PP.AM_TOTAL
FROM ITD_MT_PRODUCT_PURCHASE PP
INNER JOIN ITD_MT_PURCHASE P ON P.ID_PURCHASE = PP.ID_PURCHASE
INNER JOIN ITD_MT_CUSTOMER_LEAF CL ON CL.ID_CUSTOMER_LEAF = P.ID_CUSTOMER_LEAF
INNER JOIN ITD_MT_DISTRIBUTOR_LEAF DL ON DL.ID_DISTRIBUTOR_LEAF = PP.ID_DISTRIBUTOR_LEAF
ORDER BY 1;
